import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import PageHeader from "@/components/layout/PageHeader";
import Modal from "@/components/common/Modal";
import CurrencyDisplay from "@/components/common/CurrencyDisplay";
import Loader from "@/components/common/Loader";
import { useData } from "@/context/DataContext";
import { ASSET_CATEGORIES, ASSET_STATUSES } from "@/data/assets";

export const Route = createFileRoute("/dashboard/assets")({ component: AssetsPage });
const empty = { name: "", category: "Investment", purchaseValue: "", currentValue: "", purchaseDate: "", ownership: 100, status: "Active", description: "", image: "" };

function AssetsPage() {
  const { assets, loading, addAsset, editAsset, removeAsset } = useData();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(empty); const [error, setError] = useState("");
  function begin(item = null) { setEditing(item); setForm(item ? { ...item, purchaseDate: item.purchaseDate || "" } : empty); setError(""); setOpen(true); }
  async function submit(e) { e.preventDefault(); setError(""); try { const payload = { ...form, purchaseValue: Number(form.purchaseValue), currentValue: Number(form.currentValue), ownership: Number(form.ownership), purchaseDate: form.purchaseDate || null }; editing ? await editAsset(editing.id, payload) : await addAsset(payload); setOpen(false); } catch (x) { setError(x.message); } }
  if (loading) return <Loader label="Loading assets…" />;
  const field = "h-10 w-full rounded-xl border border-border bg-background px-3";
  return <><PageHeader title="Assets" description="Persistent records loaded from your PostgreSQL account." actions={<button onClick={() => begin()} className="flex items-center gap-2 rounded-xl brand-gradient px-4 py-2 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" />Add asset</button>} />
    <div className="overflow-hidden rounded-2xl border border-border bg-card"><table className="w-full text-sm"><thead className="bg-secondary/50 text-left"><tr><th className="p-4">Asset</th><th className="p-4">Category</th><th className="p-4 text-right">Current value</th><th className="p-4">Status</th><th className="p-4"></th></tr></thead><tbody>{assets.map((a) => <tr key={a.id} className="border-t border-border"><td className="p-4"><button className="font-semibold hover:text-primary" onClick={() => begin(a)}>{a.name}</button><div className="text-xs text-muted-foreground">Purchased {a.purchaseDate || "—"}</div></td><td className="p-4">{a.category}</td><td className="p-4 text-right font-semibold"><CurrencyDisplay value={a.currentValue} /></td><td className="p-4">{a.status}</td><td className="p-4 text-right"><button onClick={() => removeAsset(a.id)} className="rounded-lg p-2 text-muted-foreground hover:bg-negative/10 hover:text-negative"><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table>{!assets.length ? <p className="p-8 text-center text-muted-foreground">No assets yet.</p> : null}</div>
    <Modal open={open} onClose={() => setOpen(false)} title={editing ? "Edit asset" : "Add asset"} footer={<button form="asset-form" className="w-full rounded-xl brand-gradient px-4 py-2.5 font-semibold text-primary-foreground">Save asset</button>}><form id="asset-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{error ? <p className="sm:col-span-2 text-sm text-negative">{error}</p> : null}<label className="sm:col-span-2 text-sm">Name<input className={`${field} mt-1`} required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="text-sm">Category<select className={`${field} mt-1`} value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{ASSET_CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-sm">Status<select className={`${field} mt-1`} value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}>{ASSET_STATUSES.map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-sm">Purchase value<input className={`${field} mt-1`} type="number" min="0" required value={form.purchaseValue} onChange={(e) => setForm({ ...form, purchaseValue: e.target.value })} /></label><label className="text-sm">Current value<input className={`${field} mt-1`} type="number" min="0" required value={form.currentValue} onChange={(e) => setForm({ ...form, currentValue: e.target.value })} /></label><label className="text-sm">Purchase date<input className={`${field} mt-1`} type="date" value={form.purchaseDate} onChange={(e) => setForm({ ...form, purchaseDate: e.target.value })} /></label><label className="text-sm">Ownership %<input className={`${field} mt-1`} type="number" min="0" max="100" value={form.ownership} onChange={(e) => setForm({ ...form, ownership: e.target.value })} /></label><label className="sm:col-span-2 text-sm">Description<textarea className="mt-1 min-h-24 w-full rounded-xl border border-border bg-background p-3" value={form.description || ""} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label></form></Modal>
  </>;
}
