import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Plus } from "lucide-react";
import PageHeader from "@/components/layout/PageHeader";
import Modal from "@/components/common/Modal";
import Loader from "@/components/common/Loader";
import TransactionTable from "@/components/dashboard/TransactionTable";
import { useData } from "@/context/DataContext";
import { TRANSACTION_CATEGORIES, TRANSACTION_TYPES } from "@/data/transactions";

export const Route = createFileRoute("/dashboard/transactions")({ component: TransactionsPage });
const empty = { date: new Date().toISOString().slice(0, 10), title: "", type: "Expense", category: "Other", amount: "", account: "", note: "" };
function TransactionsPage() {
  const { transactions, loading, addTransaction, editTransaction, removeTransaction } = useData(); const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(empty); const [error, setError] = useState("");
  function begin(item = null) { setEditing(item); setForm(item ? { ...item } : empty); setError(""); setOpen(true); }
  async function submit(e) { e.preventDefault(); try { const raw = Math.abs(Number(form.amount)); const signed = ["Expense", "Asset purchase", "Liability payment", "Investment"].includes(form.type) ? -raw : raw; const payload = { ...form, amount: signed }; editing ? await editTransaction(editing.id, payload) : await addTransaction(payload); setOpen(false); } catch (x) { setError(x.message); } }
  if (loading) return <Loader label="Loading transactions…" />; const field = "h-10 w-full rounded-xl border border-border bg-background px-3";
  return <><PageHeader title="Transactions" description="Income and expenses persist across login sessions." actions={<button onClick={() => begin()} className="flex items-center gap-2 rounded-xl brand-gradient px-4 py-2 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" />Add transaction</button>} /><div className="overflow-hidden rounded-2xl border border-border bg-card"><TransactionTable transactions={transactions} onEdit={begin} onDelete={(x) => removeTransaction(x.id)} /></div><Modal open={open} onClose={() => setOpen(false)} title={editing ? "Edit transaction" : "Add transaction"} footer={<button form="transaction-form" className="w-full rounded-xl brand-gradient px-4 py-2.5 font-semibold text-primary-foreground">Save transaction</button>}><form id="transaction-form" onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{error ? <p className="sm:col-span-2 text-sm text-negative">{error}</p> : null}<label className="sm:col-span-2 text-sm">Title<input className={`${field} mt-1`} required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><label className="text-sm">Date<input className={`${field} mt-1`} type="date" required value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} /></label><label className="text-sm">Amount<input className={`${field} mt-1`} type="number" min="0" required value={Math.abs(Number(form.amount || 0)) || ""} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></label><label className="text-sm">Type<select className={`${field} mt-1`} value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}>{TRANSACTION_TYPES.map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-sm">Category<select className={`${field} mt-1`} value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}>{TRANSACTION_CATEGORIES.map((x) => <option key={x}>{x}</option>)}</select></label><label className="sm:col-span-2 text-sm">Account<input className={`${field} mt-1`} value={form.account || ""} onChange={(e) => setForm({ ...form, account: e.target.value })} /></label><label className="sm:col-span-2 text-sm">Note<textarea className="mt-1 min-h-20 w-full rounded-xl border border-border bg-background p-3" value={form.note || ""} onChange={(e) => setForm({ ...form, note: e.target.value })} /></label></form></Modal></>;
}
